# get http://localhost:80/node    
# post http://localhost:80/node HTTP/1.1
# Content-Type: application/json

# {
#     "title": "Hody Nguyen",
#     "description": "Test docker compose",
#     "published": true
# }



# get http://localhost:80/java/all

# post http://localhost:80/java/add?name=hody1&email=nguyenthanhdat20122002@gmail.com&age=22